# This workflow build grammars
name: Build Grammar

on:
  workflow_dispatch:
  push:
    branches: [ "main", "build" ]
  pull_request:
    types: [opened, synchronize]
    branches: [ "main", "build" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        # Repository name with owner. For example, actions/checkout
        # Default: ${{ github.repository }}
        repository: 'Myriad-Dreamin/tinymist'
        # The branch, tag or SHA to checkout. When checking out the repository that
        # triggered a workflow, this defaults to the reference or SHA for that event.
        # Otherwise, uses the default branch.
        ref: '626efa0d78388c47f6948cce3db041a8da46b639'
        # Relative path under $GITHUB_WORKSPACE to place the repository
        path: 'tinymist'
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        # Used to specify the path to a dependency file: package-lock.json, yarn.lock, etc. 
        # It will generate hash from the target file for primary key. It works only If cache is specified.  
        # Supports wildcards or a list of file names for caching multiple dependencies.
        # Default: ''
        cache-dependency-path: 'tinymist/yarn.lock'
        cache: 'yarn'
    - run: yarn install
      working-directory: tinymist
    - run: yarn compile
      working-directory: tinymist/syntaxes/textmate
    - run: |
        mv typst.tmLanguage.json typst.tinymist.tmLanguage.json
        mv typst-code.tmLanguage.json typst-code.tinymist.tmLanguage.json
        cat > feature.mts << EOF
        export const SYNTAX_WITH_BOLD_ITALIC = true;
        export const SYNTAX_WITH_MATH = true;
        export const SYNTAX_WITH_LANGS = false;
        EOF
        yarn compile
      working-directory: tinymist/syntaxes/textmate
    - name: Upload built typst.tmLanguage.json
      uses: actions/upload-artifact@v4
      with:
        name: typst.tmLanguage.json
        path: tinymist/syntaxes/textmate/typst.tmLanguage.json
    - name: Upload built typst-code.tmLanguage.json
      uses: actions/upload-artifact@v4
      with:
        name: typst.tmLanguage.json
        path: tinymist/syntaxes/textmate/typst-code.tmLanguage.json
    - name: Upload built typst.tinymist.tmLanguage.json
      uses: actions/upload-artifact@v4
      with:
        name: typst.tinymist.tmLanguage.json
        path: tinymist/syntaxes/textmate/typst.tinymist.tmLanguage.json
    - name: Upload built typst-code.tinymist.tmLanguage.json
      uses: actions/upload-artifact@v4
      with:
        name: typst.tinymist.tmLanguage.json
        path: tinymist/syntaxes/textmate/typst-code.tinymist.tmLanguage.json

